language: clojure
lein: 2.8.1
jdk:  # We only use OpenJDKs because of these shenanigans: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html
  - openjdk8
  - openjdk11
  - openjdk14

env:
  global:
    # Encrypted CLOJARS_USERNAME for Clojars deployment
    - secure: "ZCyKeBqB/5i3RTeDbWXsqVwIsMVFd/fCQ5G54U2UnmeBf/0OeFFv6Oi9b8T7yRHP3isne4QaZ4X0zEF9LIb+od8Ui/Y3/bmaAwJ0NfATBK298E2XmmtCGeE9Q/kg6HH2CQ7/Ky0UCRCi7MBSqNkPnNboEu5IZUE+Vp8JES+9xUTEoubiNn7Eapr4HTmbxVqpyOyzaNjvZxAEgSKyosw5pqjvm1qZN06gsKTUJ26JKecQA5AJltFdub5JWnzYvfIF2ar53x+o7hSixflzCm1yPc6ijkbshceiZNM8xt0Xvtntr8b2Y4Q12zPllVhRH/8R6fet2BUR/wyLmkooxcHm3p9NwT6aoGY8Wec/mpA6H6T018jUA5lLdfgDysEQX6RkMPGvtrswxHLRP6IRTGhDPKWnmmavnzGLB4wWkjNuDnOK1PyBqjRAOw8YxPAlUNBdqvJGBoxvUVFQiFyWSHIpBd9xPuLr3s1oJVl9qzo/8KyKilGI2w+D/EC1jTcncXmGzw5kZWC8En35ihQEP7I5hVsRF0mjRtehuTddPjC2xwowzUsbXWM4dQxWMzLO84zGpg1gqPuD2ZT2D577wHHHbJiy5R4h13J/MVd0qh5ynWROfaNITSCet32Ogsz3RvR7EoSMIZkGH3ObL+aZqNlZljHJYbJOEdoTfts/IaS0tP8="
    # Encrypted CLOJARS_PASSWORD for Clojars deployment
    - secure: "RnaPM676jDl8hNetq1bDjW3sxHUBzeIzn63a6OBmMK1732ymzaCRe4mNKsGbQSha28h0HZa3tTKE2/5TTMsxzogkhIq0Jvir85YBHCSULcxQhii/YPIQsYdCi8w0auyiFp+Ckqj/oqBnEzofn/GpUyKjpXXaGqMNelFcCw92DDNfSYmufhilHcaH98AeRn4Tf1iSfHYK4gyb4V2j9a4k5/tR/eIYKOxgz3JQejyeTEfdHVDgrYwdaEQhbbjySABwFTkSBgb52ZklBFqkDQgUCtB7lsLcuS1KuCEhuDfAEp64eJxk79KJ9avrWyVYSbAt2/Cz84tn3epOnZq+97bmkcb9xr3iJTRxT1gBsJuQR1x/apqGMXVr/QsXexBOCKyJGxmmw9THqRPWYtlYzEfkFaXh1adQPbBkCAY/p7fAFl3itBSoOpnD1kih0RmWeid/K5+BLI5P6D2lQp1Uk4TzRnJxaU6iKi0cndXeQrejmN+hx+9sXdmcu6R0TrkmTeIfzCQ+C97jXtXPDcouaU8PNkR1RTmkyrCc3T9ZUKM+RlyCK+yDIxN/2TsCbVYXE5TiR7ZnkHH5NAC7EMk5l2YTy0qJBmIZ2+p+xP/AFgG6DfF9rVM/E+lmNnqZt0NkCMwB/Sa8BAPJz2yNFJdCXu00EXfqbHa0VVy4WTvpb1zFmRw="
    # Encrypted GITHUB_TOKEN for gh-pages deployment
    - secure: "hnkG89MzGq5Ph8O8KHt7tineEv6w8REm9x8KonGUJt469elQdujrR9Ci+7r/jgClhbspZE+hpbPmDhAZ9N5f4ByXZi/v9AVsErmfvj9/PjAQUAPKQZ2vq7kNs3zrZxAEswdGbXGYXvHHuO7i5IYpRnKQLKe9pvuUaEN3/O/0b3IjxNGiBJQCJamiZJj30ZBt18ro30863iZNi5CpEDd/rFHYDxOsj47xltgc3ggIfYojdw1iPUD/35CiG1GgPAsGMUqs5Lka3tFPoIPobCKxrVNgvtNgG5ShmoBp/6nguDtAB5N1cnvXDiCFaJ2dlcQuYxODpcehHi43VrZgvSjNfYnRU04ZoVYuoBJXZVs2tcNRDQonYFB0pUrEjM2Upcfw6PASpI86eCLHX4S3R4CTJF5QupABqCDUoRUd7QAub6vFaHn6XSwYAONAk841uB/xj5pR6JzCHwVw42RtmlHTpy0F1aE3D8xfcnDhSavwGHoD6CRkBd9ODcsMb6a0h0OMyG7V3wo3eBjzwca6+1lnGWuoDVKYmEf9BNaSZmLiz9Y7UniOrHFWUlkRYuD4zjnjmK87IdPU+SxsU0XchjfgjMns37k2Y0iytExuR7bO8ne/BIXvqbMp3pK/L2h6Avh3efuwHDXcwdd4PZgrWUkwvcYd0lZHAoj0MTRlvVzCmZA="

before_install:
  # Install Clojure CLI tools
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
  - chmod +x linux-install-1.10.1.536.sh
  - sudo ./linux-install-1.10.1.536.sh

script:
  - export PROFILES=+1.8:+1.9
  - if [[ $JAVA_HOME != *java-7* ]]; then export PROFILES=${PROFILES}:+1.10; fi
  - lein with-profile ${PROFILES} do version, check, test
  # Check NVD database, but only on latest JDK and Clojure versions, since this step is neither version-specific, nor fast
  - if [[ $JAVA_HOME == *openjdk11* ]]; then lein with-profile +1.10 nvd check; fi

deploy:
  # Deploy SNAPSHOT binaries to Clojars (releases are manual, for now)
  - provider: script
    skip_cleanup: true
    script: lein deploy || true   # Ignore errors, since Travis CI can't currently deploy anything but snapshot versions
    on:
      branch: dev
      jdk: openjdk11
  # Generate documentation
  - provider: script
    skip_cleanup: true
    script: lein codox
    on:
      branch: master
      jdk: openjdk11
  # Deploy documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: travis+clj-symphony@finos.org
    name: Travis CI - Fintech Open Source Foundation
    local_dir: target/doc
    on:
      branch: master
      jdk: openjdk11
